INSERT INTO food (food)VALUES ('Nathans Hot Dog');
INSERT INTO food (food)VALUES ('State Fair Corn Dog');
INSERT INTO food (food)VALUES ('Bavarian Pretzel');
INSERT INTO food (food)VALUES ('Hrench Fries');
INSERT INTO food (food)VALUES ('Nachos');
INSERT INTO food (food)VALUES ('Fresh Hand Made Pizza');
INSERT INTO food (food)VALUES ('White Castle Sliders');
INSERT INTO food (food)VALUES ('Chicken Tenders');
INSERT INTO food (food)VALUES ('Buffalo Boneless Eings');
INSERT INTO food (food)VALUES ('Mozzarella Sticks');
INSERT INTO food (food)VALUES ('Wings and Fries');
INSERT INTO food (food)VALUES ('Stripes and Fries');
INSERT INTO food (food)VALUES ('Loaded Fries');
INSERT INTO food (food)VALUES ('Soda');
INSERT INTO food (food)VALUES ('Water');
INSERT INTO food (food)VALUES ('Popcorn');